### ISSUE TITLE
Commento oggetto

### ISSUE THREAD

**Issue by ElisabettaRalli** [valentinapieralice/labmod17_ex1#1]
Un bel lavoro, peccato per la mancanza di foto nel tutorial, che non mi permettono benissimo di capire come tu abbia fatto a realizzare la posata.

**Comment by valentinapieralice** [comment]
Le aggiungo subito, allora! Grazie

**Comment by valentinapieralice** [comment]
Ciao! Ho aggiunto i collegamenti delle foto, spero ora si capisca meglio.
